import React from 'react';
import { motion } from 'motion/react';
import { Button } from './ui/Button';
import { ArrowLeft, Download, Printer } from 'lucide-react';
import { useParams } from 'react-router-dom';

interface ReportProps {
  onBack: () => void;
}

export function Report({ onBack }: ReportProps) {
  const { id } = useParams();

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="report-page flex-1 bg-background p-6 md:p-12">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="report-actions flex items-center justify-between">
          <Button variant="ghost" onClick={onBack} className="gap-2 text-muted-foreground hover:text-foreground">
            <ArrowLeft className="w-4 h-4" /> Back to Dashboard
          </Button>
          <div className="flex gap-2">
            <Button variant="outline" size="icon" title="Print Report" onClick={handlePrint} className="no-print">
              <Printer className="w-4 h-4" />
            </Button>
            <Button variant="outline" size="icon" title="Download PDF" onClick={handlePrint} className="no-print">
              <Download className="w-4 h-4" />
            </Button>
          </div>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="report-card bg-white text-slate-900 rounded-xl shadow-xl border border-slate-200 overflow-hidden"
        >
          {/* Report Header */}
          <div className="border-b border-slate-200 p-8 md:p-12 bg-slate-50">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
              <div>
                <h1 className="text-3xl md:text-4xl font-serif font-bold text-slate-900 tracking-tight">
                  Aphasia Analysis Report
                </h1>
                <p className="text-slate-500 mt-2">Generated by NeuroPheno AI System</p>
              </div>
              <div className="text-left md:text-right text-sm text-slate-600 space-y-1">
                <p><span className="font-semibold">Session ID:</span> {id || 'AP-2026-0325'}</p>
                <p><span className="font-semibold">Date:</span> March 25, 2026</p>
                <p><span className="font-semibold">Duration:</span> 01:24</p>
              </div>
            </div>
          </div>

          {/* Report Body */}
          <div className="p-8 md:p-12 space-y-12">
            {/* Primary Finding */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Primary Finding</h2>
              <div className="flex items-center gap-6">
                <div className="text-5xl font-bold text-blue-600">
                  Broca's Aphasia
                </div>
                <div className="flex flex-col">
                  <span className="text-sm text-slate-500 font-medium">Confidence Score</span>
                  <span className="text-2xl font-mono font-semibold text-slate-800">92.4%</span>
                </div>
              </div>
            </section>

            {/* Detailed Explanation */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Detailed Explanation</h2>
              <div className="prose prose-slate max-w-none">
                <p className="text-slate-700 leading-relaxed">
                  The analyzed speech sample exhibits hallmark features of non-fluent aphasia. The user demonstrates significantly reduced speech rate, marked by frequent and prolonged pauses. Articulation appears effortful, and syntactic structures are simplified, consistent with agrammatism.
                </p>
                <p className="text-slate-700 leading-relaxed mt-4">
                  Comprehension indicators (derived from prompt-response latency) appear relatively preserved compared to expressive deficits. These acoustic and linguistic markers strongly align with a diagnosis of Broca's Aphasia. The model detected significant effortful speech and agrammatism, strongly correlating with patterns typical of this condition.
                </p>
              </div>
            </section>

            {/* Feature Breakdown */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Feature Breakdown</h2>
              <div className="bg-slate-50 rounded-lg border border-slate-200 p-6">
                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0" />
                    <div>
                      <h4 className="font-semibold text-slate-900">Speech Pauses (85% Impact)</h4>
                      <p className="text-slate-600 text-sm mt-1">Increased frequency and duration of pauses between words, indicating word-finding difficulty.</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0" />
                    <div>
                      <h4 className="font-semibold text-slate-900">Word Repetition (60% Impact)</h4>
                      <p className="text-slate-600 text-sm mt-1">Occasional repetition of syllables or short words during attempts to articulate complex phrases.</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0" />
                    <div>
                      <h4 className="font-semibold text-slate-900">Fluency Score (90% Impact)</h4>
                      <p className="text-slate-600 text-sm mt-1">Significantly reduced speech rate and effortful articulation, a primary marker for non-fluent aphasia.</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <div className="w-2 h-2 rounded-full bg-blue-500 mt-2 shrink-0" />
                    <div>
                      <h4 className="font-semibold text-slate-900">Syntactic Complexity (75% Impact)</h4>
                      <p className="text-slate-600 text-sm mt-1">Simplified sentence structures and omission of function words (agrammatism).</p>
                    </div>
                  </li>
                </ul>
              </div>
            </section>

            {/* Audio Insights Summary */}
            <section>
              <h2 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Audio Insights Summary</h2>
              <p className="text-slate-700 leading-relaxed">
                Analysis of the 1-minute and 24-second audio clip revealed 3 major prolonged pauses (averaging 2.4 seconds each) and 2 instances of phonemic paraphasia. Agrammatic phrasing was consistently detected throughout the middle segment of the recording.
              </p>
            </section>
          </div>
          
          {/* Footer */}
          <div className="bg-slate-50 border-t border-slate-200 p-6 text-center text-sm text-slate-500">
            <p>This report is generated by an AI system and should be reviewed by a qualified healthcare professional.</p>
            <p className="mt-1">NeuroPheno &copy; 2026</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
